### ISSUE TITLE
Backpack UAVs/UGVs Missing ACE Actions

### ISSUE THREAD

**Issue by LuizBarros99** [johnb432/AIMEE#14]
I am not entirely sure if this would be a bug, or a feature request.

Basically, I initially noticed that the AP-5 Bustard drone from the Western Sahara CDLC was missing every possible action except for the action to attach Chemlight grenades to it. This means that the actions regarding "Assembling", "Disassembling", "Connecting UAV/UGV To UAV Terminal", etc. were missing.

At first I suspected that this was merely an incompatibility problem with the Western Sahara CDLC drones not having these actions added to them. However, after testing the vanilla UAV backpacks I realized that this seems to affect every backpack UAV and UGV.

So I would like to suggest adding those features to backpack UAVs/UGVs.
Would be worth to make an observation that the "Assemble UAV/UGV" action should be on the "Self-Interaction" menu, and that the Western Sahara CDLC AP-5 Bustard and IED UAV have additional actions regarding removing and loading weapons/grenades.
Would also be worth investigating if large UAVs and UGVs also lack options to connect the UAV/UGV to the UAV terminal.

**Comment by johnb432** [comment]
> I am not entirely sure if this would be a bug, or a feature request.
> 
> Basically, I initially noticed that the AP-5 Bustard drone from the Western Sahara CDLC was missing every possible action except for the action to attach Chemlight grenades to it. This means that the actions regarding "Assembling", "Disassembling", "Connecting UAV/UGV To UAV Terminal", etc. were missing.
> 
> At first I suspected that this was merely an incompatibility problem with the Western Sahara CDLC drones not having these actions added to them. However, after testing the vanilla UAV backpacks I realized that this seems to affect every backpack UAV and UGV.
> 
> So I would like to suggest adding those features to backpack UAVs/UGVs. Would be worth to make an observation that the "Assemble UAV/UGV" action should be on the "Self-Interaction" menu, and that the Western Sahara CDLC AP-5 Bustard and IED UAV have additional actions regarding removing and loading weapons/grenades. Would also be worth investigating if large UAVs and UGVs also lack options to connect the UAV/UGV to the UAV terminal.

It's a feature request, as the actions you describe were never added. They will be added in the next update, which will come out when ACE 3.16.0 releases.

I'm not going to bring special compatibility between AIMEE and WS though. I'm not motivated enough to do it and don't see the point for a handful of unique actions.

**Comment by johnb432** [comment]
@LuizBarros99 Check if the issue has been addressed.

**Comment by johnb432** [comment]
Considered to be resolved.
